/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "from@0": {
      "transform": [{
        "rotate": "0deg"
      }]
    },
    "to@0": {
      "transform": [{
        "rotate": "360deg"
      }]
    },
    "root": {
      "display": "flex",
      "alignItems": "center",
      "borderTopLeftRadius": 12,
      "borderTopRightRadius": 12,
      "borderBottomRightRadius": 12,
      "borderBottomLeftRadius": 12,
      "flexDirection": "row",
      "height": 24,
      "paddingTop": 0,
      "paddingRight": 8,
      "paddingBottom": 0,
      "paddingLeft": 8,
      "backgroundColor": "transparent",
      "borderWidth": 0,
      "borderColor": "black",
      "borderStyle": "solid"
    },
    "root:hover@0": {
      "backgroundColor": "rgba(51, 51, 51, 1)"
    },
    "root:active": {
      "backgroundColor": "rgba(51, 51, 51, 0.6)"
    },
    "image": {
      "height": 14,
      "width": 16,
      "marginRight": 4
    },
    "text": {
      "fontSize": 12,
      "lineHeight": 16
    }
  },
  atRules: {
    "from": [[["keyframes", "spin"]]],
    "to": [[["keyframes", "spin"]]],
    "root:hover": [[["media", "(hover: hover)"]]]
  },
  transforms: {
    "from": true,
    "to": true
  }
});